use_frameworks!
platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'                                         # CDN

target 'KLTimeMeter_Example' do
  pod 'KLTimeMeter', :path => '../'
  pod 'MJRefresh'
  
  target 'KLTimeMeter_Tests' do
    inherit! :search_paths

    
  end
end
